### ISSUE TITLE
Mustang Controller Dumps

### ISSUE THREAD

**Issue by LaughDonor** [wirelessdreamer/game2midi#1]
Apologies for being a decade late, but is there any chance you that may have a record of the Mustang Controller Dumps? RB4 wiped their forums, the Wayback Machine, and Google Cache doesn't seem to have that data either. 

I'm specifically looking to see if that controller had sent some initialization data on power up or connection and if the controller streams any data while idle.

I'm really impressed by your documentation and article in the Linux Journal on this, as that's helped a lot too.

Thanks!

**Comment by wirelessdreamer** [comment]
I don't have any dumps on hand, but I bought one of the controllers to mess with recently, so I'll try and get you a dump later today. Feel free to ping the thread if it feels like I drop off, get distracted, and forget :)

**Comment by wirelessdreamer** [comment]
No to all 3 questions, sysex messages are only sent on button state changes, or when a string is played.

On a separate note, If I have some free time down the road, I've been thinking about porting this to c# for unity, so I could have a virtual instrument that runs on quest. I don't have time to write it now, but if by chance your doing something similar, I'd be happy to help test.
